INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G1");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G2");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G3");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G3X");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G3//");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G3B");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G4E");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gamba G5A");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Langostino Mauritania 2");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Langostino Mauritania 4");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Langostino Mauritania 5");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Langostino Trasmallo M");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Langostino Trasmallo XL");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Pulpo CH Rejos Cocidos");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Pulpo GR 1/2kg");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Buey de Mar");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Tortilla Camarón 1/2kg");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Tortilla Gamba 1/2kg");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Cola Gamba Mozambique");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Cola Gambón 2kg");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Cigala Grillo");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Gigala Tronco");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Choco en tiras");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Choco Entero");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Hueva Choco 250gr ");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Acedias Marruecos");
--
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Hueva Choco");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Cola Gambón");
INSERT INTO `mydb`.`tipoproducto` (`tipo`) VALUES ("Hueva Bacalao");